// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Abc: typeof import('./src/pages/dashboard/components/not-route.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    FooterContent: typeof import('./src/components/FooterContent.vue')['default']
    Language: typeof import('./src/components/Language.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NotRoute: typeof import('./src/pages/dashboard/components/not-route.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
  }
}
